// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/v1/service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetStreetViewRequest struct {
	CorrelationId        string   `protobuf:"bytes,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Latitude             float32  `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStreetViewRequest) Reset()         { *m = GetStreetViewRequest{} }
func (m *GetStreetViewRequest) String() string { return proto.CompactTextString(m) }
func (*GetStreetViewRequest) ProtoMessage()    {}
func (*GetStreetViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89fdd0f41cb65e4f, []int{0}
}

func (m *GetStreetViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreetViewRequest.Unmarshal(m, b)
}
func (m *GetStreetViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreetViewRequest.Marshal(b, m, deterministic)
}
func (m *GetStreetViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreetViewRequest.Merge(m, src)
}
func (m *GetStreetViewRequest) XXX_Size() int {
	return xxx_messageInfo_GetStreetViewRequest.Size(m)
}
func (m *GetStreetViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreetViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreetViewRequest proto.InternalMessageInfo

func (m *GetStreetViewRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *GetStreetViewRequest) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GetStreetViewRequest) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type GetStreetViewResponse struct {
	Image                []byte   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStreetViewResponse) Reset()         { *m = GetStreetViewResponse{} }
func (m *GetStreetViewResponse) String() string { return proto.CompactTextString(m) }
func (*GetStreetViewResponse) ProtoMessage()    {}
func (*GetStreetViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89fdd0f41cb65e4f, []int{1}
}

func (m *GetStreetViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreetViewResponse.Unmarshal(m, b)
}
func (m *GetStreetViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreetViewResponse.Marshal(b, m, deterministic)
}
func (m *GetStreetViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreetViewResponse.Merge(m, src)
}
func (m *GetStreetViewResponse) XXX_Size() int {
	return xxx_messageInfo_GetStreetViewResponse.Size(m)
}
func (m *GetStreetViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreetViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreetViewResponse proto.InternalMessageInfo

func (m *GetStreetViewResponse) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func init() {
	proto.RegisterType((*GetStreetViewRequest)(nil), "v1.GetStreetViewRequest")
	proto.RegisterType((*GetStreetViewResponse)(nil), "v1.GetStreetViewResponse")
}

func init() { proto.RegisterFile("api/proto/v1/service.proto", fileDescriptor_89fdd0f41cb65e4f) }

var fileDescriptor_89fdd0f41cb65e4f = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x6a, 0x84, 0x30,
	0x10, 0xc6, 0xab, 0xa5, 0xa5, 0x0e, 0xed, 0xa1, 0x83, 0x05, 0x2b, 0x3d, 0x88, 0xf4, 0xe0, 0xa5,
	0x8a, 0xed, 0x43, 0x14, 0xe9, 0x2d, 0x42, 0xcf, 0xb5, 0x3a, 0x48, 0xc0, 0x35, 0x6e, 0x12, 0xe3,
	0xeb, 0x2f, 0x26, 0xb0, 0x8b, 0x8b, 0xb7, 0x7c, 0x7f, 0xc8, 0x8f, 0x6f, 0x20, 0x6e, 0x26, 0x5e,
	0x4c, 0x52, 0x68, 0x51, 0x98, 0xb2, 0x50, 0x24, 0x0d, 0x6f, 0x29, 0xb7, 0x06, 0xfa, 0xa6, 0x4c,
	0x0d, 0x84, 0xdf, 0xa4, 0x6b, 0x2d, 0x89, 0xf4, 0x2f, 0xa7, 0x85, 0xd1, 0x71, 0x26, 0xa5, 0xf1,
	0x1d, 0x9e, 0x5a, 0x21, 0x25, 0x0d, 0x8d, 0xe6, 0x62, 0xac, 0xba, 0xc8, 0x4b, 0xbc, 0x2c, 0x60,
	0x5b, 0x13, 0x63, 0x78, 0x58, 0xdf, 0x7a, 0xee, 0x28, 0xf2, 0x13, 0x2f, 0xf3, 0xd9, 0x59, 0xe3,
	0x1b, 0x04, 0x83, 0x18, 0x7b, 0x17, 0xde, 0xda, 0xf0, 0x62, 0xa4, 0x1f, 0xf0, 0x72, 0xc5, 0x55,
	0x93, 0x18, 0x15, 0x61, 0x08, 0x77, 0xfc, 0xd0, 0xf4, 0x64, 0x81, 0x8f, 0xcc, 0x89, 0xcf, 0x3f,
	0x78, 0x76, 0x5d, 0xc3, 0x69, 0xa9, 0xdd, 0x0a, 0xfc, 0x01, 0xdc, 0xfc, 0x51, 0xad, 0x55, 0x8c,
	0x72, 0x53, 0xe6, 0x7b, 0x9b, 0xe2, 0xd7, 0x9d, 0xc4, 0x51, 0xd3, 0x9b, 0xff, 0x7b, 0x7b, 0x93,
	0xaf, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xb6, 0xbd, 0xc5, 0x31, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreetviewServiceClient is the client API for StreetviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreetviewServiceClient interface {
	GetStreetViewImage(ctx context.Context, in *GetStreetViewRequest, opts ...grpc.CallOption) (*GetStreetViewResponse, error)
}

type streetviewServiceClient struct {
	cc *grpc.ClientConn
}

func NewStreetviewServiceClient(cc *grpc.ClientConn) StreetviewServiceClient {
	return &streetviewServiceClient{cc}
}

func (c *streetviewServiceClient) GetStreetViewImage(ctx context.Context, in *GetStreetViewRequest, opts ...grpc.CallOption) (*GetStreetViewResponse, error) {
	out := new(GetStreetViewResponse)
	err := c.cc.Invoke(ctx, "/v1.StreetviewService/GetStreetViewImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreetviewServiceServer is the server API for StreetviewService service.
type StreetviewServiceServer interface {
	GetStreetViewImage(context.Context, *GetStreetViewRequest) (*GetStreetViewResponse, error)
}

func RegisterStreetviewServiceServer(s *grpc.Server, srv StreetviewServiceServer) {
	s.RegisterService(&_StreetviewService_serviceDesc, srv)
}

func _StreetviewService_GetStreetViewImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreetViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreetviewServiceServer).GetStreetViewImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.StreetviewService/GetStreetViewImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreetviewServiceServer).GetStreetViewImage(ctx, req.(*GetStreetViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreetviewService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.StreetviewService",
	HandlerType: (*StreetviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStreetViewImage",
			Handler:    _StreetviewService_GetStreetViewImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/service.proto",
}
