version: "3"
services:
  palmago-app:
    image: golang:latest
    container_name: palmago-app
    hostname: palmago-app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app/logs:/tmp
    environment:
      - "STREETVIEW_API_ENDPOINT=${STREETVIEW_API_ENDPOINT}"
      - "STREETVIEW_API_KEY=${STREETVIEW_API_KEY}"
      - "STREETVIEW_API_IMAGE_HEIGHT=${STREETVIEW_API_IMAGE_HEIGHT}"
      - "STREETVIEW_API_IMAGE_WIDTH=${STREETVIEW_API_IMAGE_WIDTH}"
      - "STREETVIEW_API_IMAGE_FOV=${STREETVIEW_API_IMAGE_FOV}"
      - "STREETVIEW_API_RETRY_DELAY=${STREETVIEW_API_RETRY_DELAY}"
      - "STREETVIEW_API_MAX_RETRIES=${STREETVIEW_API_MAX_RETRIES}"
      - "WEBSERVER_LISTEN_PORT=${WEBSERVER_LISTEN_PORT}"
      - "GRPC_SERVER_PROTOCOL=${GRPC_SERVER_PROTOCOL}"
      - "GRPC_SERVER_HOST=${GRPC_SERVER_HOST}"
      - "GRPC_SERVER_PORT=${GRPC_SERVER_PORT}"
      - "GRPC_SERVER_RETRY_DELAY=${GRPC_SERVER_RETRY_DELAY}"
      - "GRPC_SERVER_MAX_RETRIES=${GRPC_SERVER_MAX_RETRIES}"
      - "ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}"
      - "ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}"
      - "ELASTICSEARCH_INDEX=${ELASTICSEARCH_INDEX}"
      - "ELASTICSEARCH_RETRY_DELAY=${ELASTICSEARCH_RETRY_DELAY}"
      - "ELASTICSEARCH_MAX_RETRIES=${ELASTICSEARCH_MAX_RETRIES}"
      - "ELASTICSEARCH_EXPOSED_PORT=${ELASTICSEARCH_EXPOSED_PORT}"
      - "ELASTICSEARCH_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}"
      - "KIBANA_PORT=${KIBANA_PORT}"
      - "REDIS_HOST=${REDIS_HOST}"
      - "REDIS_PORT=${REDIS_PORT}"
      - "REDIS_RETRY_DELAY=${REDIS_RETRY_DELAY}"
      - "REDIS_MAX_RETRIES=${REDIS_MAX_RETRIES}"
    ports:
      - "${WEBSERVER_LISTEN_EXPOSED_PORT}:${WEBSERVER_LISTEN_PORT}"
      - "${GRPC_SERVER_EXPOSED_PORT}:${GRPC_SERVER_EXPOSED_PORT}"

    networks:
      - palmago-net

networks:
  palmago-net:
    external: true