version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: palmago-elasticsearch
    hostname: palmago-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}"
    volumes:
      - "./elasticsearch/shared-data:/usr/share/elasticsearch/data"
    ports:
      - "${ELASTICSEARCH_EXPOSED_PORT}:${ELASTICSEARCH_PORT}"
    networks:
      - palmago-net

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: palmago-kibana
    hostname: palmago-kibana
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    ports:
      - "${KIBANA_EXPOSED_PORT}:${KIBANA_PORT}"
    links:
      - elasticsearch
    networks:
      - palmago-net

networks:
  palmago-net:
    external: true
